multiuser/classroom/urls.py
from django.urls import path
from . import views
app_name = 'classroom'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('student_register/',views.student_registration,name='student_register'),
    path('teacher_register/',views.teacher_registration,name='teacher_register'),
    path('welcome/',views.welcome,name='welcome'),
]

multiuser/multiuser/urls.py
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path('classroom/', include('classroom.urls',namespace='classroom')),
    path('admin/',admin.site.urls),
]

multiuser/classroom/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)

    def __str__(self):
        return self.username


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

multiuser/classroom/forms.py
from django import forms
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

multiuser/classroom/views.py
from django.shortcuts import render,redirect, HttpResponse
from django.contrib.auth import login, authenticate, logout
from .forms import LoginForm
from .models import User,Student,Teacher


def register(request):
    return render(request,'classroom/register.html')

def welcome(request):
    return render(request,'classroom/welcome.html')

def student_registration(request):
    if request.method == 'POST':
        if request.POST['password'] == request.POST['passagain']:
            try:
                User.objects.get(username=request.POST['username'])
                return render(request,'classroom/student_register.html',{'error':'User is already taken'})
            except User.DoesNotExist:
                user = User(username=request.POST['username'],
                            email=request.POST['email'],
                            first_name=request.POST['first_name'],
                            last_name=request.POST['last_name'],
                            is_student=True)

                user.set_password(request.POST['password'])
                user.save()
                student=Student.objects.create(user=user)
                return redirect('/classroom/login/')
        else:
            return render(request, 'classroom/student_register.html', {'error': 'Password not matched'})
    else:
        return render(request,'classroom/student_register.html')

def teacher_registration(request):
    if request.method == 'POST':
        if request.POST['password'] == request.POST['passagain']:
            try:
                User.objects.get(username=request.POST['username'])
                return render(request,'classroom/teacher_register.html',{'error':'User is already taken'})
            except User.DoesNotExist:
                user = User(username=request.POST['username'],
                            email=request.POST['email'],
                            first_name=request.POST['first_name'],
                            last_name=request.POST['last_name'],
                            is_teacher=True,
                            is_superuser=True)

                user.set_password(request.POST['password'])
                user.save()
                teacher=Teacher.objects.create(user=user)
                return redirect('/classroom/login/')
        else:
            return render(request, 'classroom/teacher_registration.html', {'error': 'Password not matched'})
    else:
        return render(request,'classroom/teacher_registration.html')


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user.is_student:
                login(request, user)
                return render(request,'classroom/welcome_student.html/')
            if user.is_teacher:
                login(request, user)
                return render(request,'classroom/welcome_teacher.html/')
            else:
                login(request,user)
                return render(request, 'classroom/welcome.html/')
        else:
            return render(request, 'classroom/login.html', {'form': form,
                                                  'error': 'invalid credentials'})
    else:
        form = LoginForm()
    return render(request,'classroom/login.html',{'form':form})


def logout_view(request):
    logout(request)
    return redirect('/classroom/login/')

multiuser/classroom/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <title>Title</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">MultiUser example</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'classroom:logout' %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'classroom:login' %}">Login</a>
      </li>
      {% endif %}
    </ul>
    <span class="navbar-text">
      Navbar text with an inline element
    </span>
  </div>
</nav>
{% block bodyblock %}
{% endblock %}
</body>
</html>

multiuser/classroom/templates/classroom/login.html
{% extends 'base.html' %}
{% block bodyblock %}

<div class="jumbotron">
    <center><h2>Login Here</h2></center>
 <div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-body">
          {% if error %}
          {{ error }}
          {% endif %}
          <form method="post" novalidate>
              {% csrf_token %}
              {{ form.as_p }}
              <input type="submit" value="Login">
          </form>
      </div>
    </div>
  </div>
 </div>
</div>

{% endblock %}

multiuser/classroom/templates/classroom/register.html
{% extends 'base.html' %}
{% block bodyblock %}
<div class="jumbotron">
    <center>
        <h2>Register</h2>
        <div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <a href="{% url 'classroom:student_register' %}" class="btn btn-primary">I'm a student</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <a href="{% url 'classroom:teacher_register' %}" class="btn btn-primary">I'm a teacher</a>
      </div>
    </div>
  </div>
</div>
    </center>
</div>
{% endblock %}

multiuser/classroom/templates/classroom/student_register.html
{% extends 'base.html' %}
{% block bodyblock %}

<div class="jumbotron">
    <center><h2>Student Registration</h2></center>
 <div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-body">
          {% if error %}
          {{ error }}
          {% endif %}
          <form method="POST" novalidate>
              {% csrf_token %}
              <input type="text" name='username' placeholder="username">
              <input type="email" name='email' placeholder="email">
              <input type="text" name='first_name' placeholder="firstname">
              <input type="text" name='last_name' placeholder="lastname">
              <input type="password" name='password' placeholder="password">
              <input type="password" name='passagain' placeholder="confirm password">
              <input type="submit" value="Register">

          </form>
      </div>
    </div>
  </div>
 </div>
</div>

{% endblock %}

multiuser/classroom/templates/classroom/teacher_registration.html
{% extends 'base.html' %}
{% block bodyblock %}

<div class="jumbotron">
    <center><h2>Teacher Registration</h2></center>
 <div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-body">
          {% if error %}
          {{ error }}
          {% endif %}
          <form method="POST" novalidate>
              {% csrf_token %}
              <input type="text" name='username' placeholder="username">
              <input type="email" name='email' placeholder="email">
              <input type="text" name='first_name' placeholder="firstname">
              <input type="text" name='last_name' placeholder="lastname">
              <input type="password" name='password' placeholder="password">
              <input type="password" name='passagain' placeholder="confirm password">
              <input type="submit" value="Register">

          </form>
      </div>
    </div>
  </div>
 </div>
</div>

{% endblock %}

multiuser/classroom/templates/classroom/welcome.html
{% extends 'base.html' %}
{% block bodyblock %}
<center>
    <h1>You are logged as guest </h1>
</center>
{% endblock %}

multiuser/classroom/templates/classroom/welcome_student.html
{% extends 'base.html' %}
{% block bodyblock %}
<center>
    <h1>You have successfully loggedin as Student !</h1>
</center>
{% endblock %}

multiuser/classroom/templates/classroom/welcome_teacher.html
{% extends 'base.html' %}
{% block bodyblock %}
<center>
    <h1>You have successfully loggedin as Teacher !</h1>
</center>
{% endblock %}